#update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ensure_git_status_clean
    clean_build_artifacts
    clear_derived_data
  end

  desc "Upload App To TestFlight"
  lane :beta do

    enable_automatic_code_signing
    increment_build_number
    commit_version_bump
    gym
    build_app
    pilot(skip_waiting_for_build_processing: true) #This means that no changelog will be set and no build will be distributed to testers
    end

  end
